model:
  _target_: main.XGboost
  export_dir: ???
  cfg:
    n_estimators: 100
    n_jobs: -1
    max_depth: 8
    eta: 1e-3
    subsample: 0.5
    sampling_method: "gradient_based"
    objective: "reg:squarederror"
    tree_method: "gpu_hist"


name: "Xgboost"