epochs: 100
val_compare_file: True
use_kfold: False
kfold_agg: False

optimizer:
  _target_: torch.optim.Adam
  params: ???
  lr: 1e-2
  weight_decay: 5e-8


criterion:
  _target_: torch.nn.MSELoss
  reduction: "mean"